# Generated by Django 2.0 on 2019-02-07 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('comentarios', '0003_comentario_status'),
        ('localizacao', '0001_initial'),
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.BooleanField()),
                ('foto', models.ImageField(upload_to='img')),
                ('atracao', models.ManyToManyField(to='eventos.Atracao')),
                ('avaliacao', models.ManyToManyField(to='avaliacoes.Avaliacao')),
                ('comentarios', models.ManyToManyField(to='comentarios.Comentario')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacao.Endereco')),
            ],
            options={
                'verbose_name': 'Ponto Turistico',
                'verbose_name_plural': 'Ponto Turisticos',
            },
        ),
    ]
