# Generated by Django 2.0 on 2019-02-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20190205_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
