# Generated by Django 2.0 on 2019-02-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha1', models.CharField(max_length=100, verbose_name='Rua')),
                ('linha2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Outros')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
            ],
        ),
    ]
